language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: iFX9Oow9vF3jIIWEL3Y0qNyoftH4efTQStNh5pMjpOFh7pYbLhi6JY4DYXHPD6E6l2Vo9UomLzYkVoHYX86e70HRV528bnSQsFplFE0p7NT+aSPQxBo4cuDHrvrJWwcALgTf/vEYQ/D2S32QxOjXAqmJouQsKJOcW9I4eReNafSdSInwrmBxkF5USXYr1x93U7sZ2lJtildeyPj1jqMpEwUJ2r03sF5BQaEjPH82dVKXiwmckTRLcWjUx5RrmIcQ4+4bZi9GA/h2ZY1Rw617ge4C1Lx9DNca4OCzRjnGuD3jDOyFDvNUk5gmk4XeiNpQwzS9sBnxtTDzNXKppw+ZjmtBWNnJaTb+V2DKxhnh7QD4gkCqaYZc1O9tuH2fCxyiE8ZGWhZsYC7A8/wr5qWF42z95eCKZ9qBSNkwAIyaDYCYRJ3yKoFdlpl81SMMQR+e7qd73So3qRubynIYyqObWtdmZPp1lLcCIt0rNTbh0AKp9KaYqUB1Yg/8dLoRqBEH4ClhSfaGWZNKHOzjPl0Tot3KKgMuufwG0XK1hfz2sZroQxDegKBWS3FDHwWpxHfv6XjwjKCtaCJzDww9SzDDWE6zUwdGm+OfWWUz6Z+SoEuh4wWG3URuNEyqfCWjFBjgnerkOtWwEunD2nDdj4XYBD5r+ZcHUAIF8xZOtLltPAY=
  app: stormy-tundra-36765
  on:
    repo: J-Vega/HooIsIt
